### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by olistik**
Some house cleaning ;-)

### CODE REVIEW

**Comment by raggi** [comment]
The tarballs have more content in them and the sha's are there for verification, please don't remove them.

**Comment by olistik** [comment]
@raggi which SHA command has been used to obtain such checksums?

**Comment by olistik** [comment]
@raggi I'd be more than happy to include the missing SHA checksums but I couldn't match the old checksums.

For example, for the 1.4.1 release ([link](https://github.com/rack/rack.github.com/blob/master/index.html#L248)) the checksum is `e822bb1c1dd9306f1f4cc6c7c208ac3fe0aa4018`.
But if I download the [1.4.1 tar.gz available on Github](https://github.com/rack/rack/archive/1.4.1.tar.gz) the checksum I obtain is `ae275fd86af65d234bdcdb2234790b6bb2c0bcd1`: 

```bash
ಠ_ಠ shasum rack-1.4.1.tar.gz
ae275fd86af65d234bdcdb2234790b6bb2c0bcd1  rack-1.4.1.tar.gz
```

The [Rubygems page](https://rubygems.org/gems/rack/versions/1.4.1) already provides a checksum.

Moreover the tar.gz hosted on `http://chneukirchen.org` give an HTTP 404..

```bash
ಠ_ಠ wget http://chneukirchen.org/releases/rack-1.4.1.tar.gz
--2015-04-09 16:28:46--  http://chneukirchen.org/releases/rack-1.4.1.tar.gz
Resolving chneukirchen.org... 24.75.24.250, 2001:470:1f07:1247:218:51ff:fec8:2476
Connecting to chneukirchen.org|24.75.24.250|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-04-09 16:28:46 ERROR 404: Not Found.
```

**Comment by chneukirchen** [comment]
Maurizio De Magnis <notifications@github.com> writes:

> @raggi I'd be more than happy to include the missing SHA checksums but
> I couldn't match the old checksums.
>
> For example, for the 1.4.1 release
> ([link](https://github.com/rack/rack.github.com/blob/master/index.html#L248))
> the checksum is `e822bb1c1dd9306f1f4cc6c7c208ac3fe0aa4018`.
> But if I download the [1.4.1 tar.gz available on
> Github](https://github.com/rack/rack/archive/1.4.1.tar.gz) the
> checksum I obtain is `ae275fd86af65d234bdcdb2234790b6bb2c0bcd1`:
>
> ```bash
> ಠ_ಠ shasum rack-1.4.1.tar.gz
> ae275fd86af65d234bdcdb2234790b6bb2c0bcd1  rack-1.4.1.tar.gz
> ```
>
> The [Rubygems page](https://rubygems.org/gems/rack/versions/1.4.1)
> already provides a checksum.
>
> Moreover the tar.gz hosted on `http://chneukirchen.org` give an HTTP 404..
>
> ```bash
> ಠ_ಠ wget http://chneukirchen.org/releases/rack-1.4.1.tar.gz
> --2015-04-09 16:28:46--  http://chneukirchen.org/releases/rack-1.4.1.tar.gz
> Resolving chneukirchen.org... 24.75.24.250, 2001:470:1f07:1247:218:51ff:fec8:2476
> Connecting to chneukirchen.org|24.75.24.250|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2015-04-09 16:28:46 ERROR 404: Not Found.
> ```

There is no 1.4.1 there, interesting.  AFAICS I never had a tarball
for that one.  Just drop it from the list?

Usually the SHASUM should agree with the version hosted on my site
(i.e. release tarballs).

-- 
Christian Neukirchen  <chneukirchen@gmail.com>  http://chneukirchen.org

**Comment by raggi** [comment]
@tenderlove @chneukirchen you guys should figure this out for future releases as I don't think the process is the same anymore and so maybe we just want to rely on the rubygems ones now instead. I'll leave it to you.

**Comment by dideler** [comment]
Given that GitHub has the tarballs and RubyGems has the checksums, are there any concerns blocking this from going out?

FWIW I came across the Rack website before the GitHub repo and for a moment thought that the project was no longer maintained as the last news update was almost 3 years ago.

**Comment by olistik** [comment]
Ping? :-)

**Comment by glaucocustodio** [comment]
Is something missing to merge this PR? Let's keep rack's website updated ;). Can anybody merge it please?

**Comment by raggi** [comment]
If no users ever care about verification or the changelogs, then just linking to rubygems.org is ok. The SHA's shouldn't line up with github releases pages, as those older release are not just copies of a repo snapshot, they include generated files. See the https://github.com/rack/rack/blob/master/Rakefile for more details.

**Pull request closed without merging**
